### ISSUE TITLE
[Question] What to use for error message / warning?

### ISSUE THREAD

**Issue by Potherca** [andybrewer/mvp#110]
First, let me say: I've been using MVP.css for some proof-of-concepts. I love how light-weight it is, how clean and crisp the UI looks and how fully-featured it is. Great work!

I was wondering if you might have some advice for me. The thing I am unsure about is how to deal with the scenario of showing the user an error message or warning. I can't really find a semantic HTML element for this. The `<dialog>` works for generic messaging, but I can't decide how to best deal with errors, specifically.

What would one do, in the context of MVP.css, to show the user an error? Any thoughts/feedback would be much appreciated!

**Comment by bueltge** [comment]
I would use in this case the figure tag. My source for this decision is often [HTML5 doctor](http://html5doctor.com/the-figure-figcaption-elements/)

```html
<figure id="dialog-box" class="error" role="alert">
    <figcaption>Error Message Title</figcaption>
    <p>Error Message text</p>
</figure>
```

We could use the role attribute from aria to format them via CSS.

```css
[role="alert"] {
  font-size: 2em;
  color: red;
}
```

**Comment by ChristopherBilg** [comment]
@bueltge's approach is a great method to accomplish this. Unfortunately, semantic HTML doesn't have a great solution for ephemeral error messages, toasts, etc.

**Comment by Potherca** [comment]
For inline messages I ended up using this:

```html
<main>
    <section>
        <figure role="alert">
            <figcaption>Error Message Title</figcaption>
            <p>Error message text</p>
        </figure>
    </section>	
</main>
```

And for modal messages this:
```html
<dialog open role="alertdialog">
    <form method="dialog">
        <figure>
            <figcaption>Error Message Title</figcaption>
            <p>Error message text</p>
        </figure>
        <button autofocus>Close</button>		
    </form>
</dialog>
```

With some minimal styling, the result is quite satisfactory, IMHO.

```css
:root {--color-alert: crimson;}

[role="alert"] figcaption, [role="alertdialog"] figcaption {font-size: 2em; color: var(--color-alert);}
[role="alertdialog"] {padding:0;border-color:var(--color-alert);max-width: var(--width-card-wide);}
[role="alertdialog"] button {background-color:var(--color-alert);border-color:var(--color-alert)}
[role="alertdialog"] form {margin-bottom:0;}
```

![image](https://github.com/andybrewer/mvp/assets/195757/c1685ecd-44a2-49e1-9108-ebd921e69437)

Live example can be found at https://gist.pother.ca/2a9a3ffc6fdfb14bc67f88b03e984332/

 - - -
 
 I'm thinking that `<dialog role="alert">` might also work well css-only (i.e. without being a modal window).
