### ISSUE TITLE
Support for menu on mobile

### ISSUE THREAD

**Issue by Potherca** [andybrewer/mvp#120]
As I [mentioned in #21][1], having generic support for the menu on mobile would be most awesome.

So I had a stab at making a backward-compatible, CSS only, plug-and-play implementation.

It can be seen in action at https://contrib.pother.ca/MetroJS/examples/

(Make sure to resize the screen to less than 800px or increase the font-size x8.

Part of the CSS could be removed, as it is copy-pasted from existing mvp.css code.

<details><summary><b>The CSS is thus</b> (click to toggle)</summary>

```css
/* Menu on mobile devices */
:root {
  --menu-label:'Toggle Menu';
}
nav > button:empty,
nav > button[aria-controls] {
  display: none;
}

@media (max-width: 768px) {
  nav > ul {
    background: var(--color-bg);
    bottom: 0;
    display: none;
    height: fit-content;
    left: 0;
    margin: 0;
    max-height: 100%;
    overflow: auto;
    position: fixed;
    right: 0;
    top: 0;
  }

  nav > button:empty,
  nav > button[aria-controls] {
    cursor: pointer;
    display: inline-block;
  }

  nav > button:empty::before {
    content: attr(aria-label, var(--menu-label));
  }

  nav > button:empty:focus,
  nav > button[aria-controls]:focus {
    opacity: 0;
  }

  nav:has(button:empty) > ul::before,
  nav:has(button[aria-controls]) > ul::before {
    /* FROM: a b, a strong, button, input[type="submit"] */
    background-color: var(--color-link);
    border: 2px solid var(--color-link);
    color: var(--color-bg);

    /* FROM: a b, a em, a i, a strong, button, input[type="submit"] */
    border-radius: var(--border-radius);
    display: block;
    font-size: medium;
    font-weight: bold;
    line-height: var(--line-height);
    padding: 1rem 2rem;

    /* Element specific */
    content: attr(aria-label, var(--menu-label));
    cursor: pointer;
    float: right;
    margin: 0.75rem 1rem 0.5rem 0;
  }

  nav:focus-within > ul,
  nav:has(button:empty:focus) > ul,
  nav:has(button[aria-controls]:focus) > ul {
    display: block;
  }

  nav ul li {
    width: calc(100% - 1em);
  }

  nav ul li ul {
    display: block;
    position: static;
  }
}
```

</details>

To activate it, a `<button>` needs to be added in the `<nav>`. This can be an empty button:

```html
<header>
    <nav>
        <button></button> <!-- ⬅️ This needs to be added -->
        <ul>
                <li>Menu Item 1</li>
                <!-- etc. -->
            </ul>
```
A `--menu-label` is added to allow easy changing the toggle button text.

A fully fledge (almost) [aria compliant button][2] could also be used:

```html
<header>
    <nav>
        <button
            aria-controls="menu"
            aria-expanded="false"
            aria-label="Toggle Menu"
            onfocusin="this.setAttribute('aria-expanded', 'true')"
            onfocusout="this.setAttribute('aria-expanded', 'false')"
            onkeydown="if (event.keyCode === 27) this.blur()"
        >Open Menu</button>
        <ul id="menu" aria-label="Close Menu">
                <li>Menu Item 1</li>
                <!-- etc. -->
            </ul>
```
The only thing that doesn't comply is that the close button can not be tabbed to.
Everything else "just works" as the menu is not opened unless tabbed to.

So... Thoughts?

[1]: https://github.com/andybrewer/mvp/issues/21#issuecomment-2308178764
[2]: https://theadminbar.com/accessibility-weekly/mobile-nav-and-hamburger-menus/

**Comment by ChristopherBilg** [comment]
Besides cleaning up the CSS, I'm also not a fan of the non-compliance for closing the menu. It looks like @andybrewer had some opinions as well in #21. This is nice so long as it's not opinionated regarding styling, etc.

Can we look into making the menu compliant and then I can take a sweep on removing CSS that was copy/pasted and isn't needed?

**Comment by Potherca** [comment]
Thank you for the feedback! 

<details><summary><b>Full thought, in order</b> (click to toggle)</summary>
 
1. > I'm also not a fan of the non-compliance for closing the menu

    That's been bugging me as well. The only two solutions I can think of that are pure CSS/HTML are:
    
    1. adding another button inside the menu
    2. using the input[type="checkbox"] & label as done in #21.
    
    Or both? 🤷 I could code an example for either for easier comparison.
    
    Both solutions need HTML tags to be added. The question then becomes if that is acceptable. An/or which one is more acceptable.

2. > It looks like @andybrewer had some opinions as well in #21.

    The major opinion seems to be:
    
    >  I think it might be a little too custom for this project
    
    Which motivated me to try to create something that is "of this project", reusing as much as possible of the MVP.css code, aesthetic and philosophy. However, It won't be possible to create something that just works with only the existing ul -> li HTML structure. _Something_ will have to be added (i.e. an HTML tag) in order to have a hook to hang everything on. 
    
    The more ARIA compliant, the larger that "something" becomes. Finding the right balance and an elegant solution is what makes this challenge fun, IMHO.
    
3. > This is nice so long as it's not opinionated regarding styling, etc.

    100% agree. I've tried to make it look as much in style as possible. It might need another round of work. For me, the main success criterion is that it _has_ to look "in place" (i.e. not look out-of-place).

4. > Can we look into making the menu compliant

    I can set up examples for that, as mentioned above. I'll post links here when complete.

5. > then I can take a sweep on removing CSS that was copy/pasted and isn't needed?

    The copy/pasted CSS is only needed until `nav:has(button:empty) > ul::before` and/or `nav:has(button[aria-controls]) > ul::before` are added to the `a b, a strong, button, input[type="submit"]` selector (depending on what the final implementation will be). Although, thinking about it, if compliance it reached the `::before` isn't needed so the point becomes moot.
    
    At this point all CSS present is needed, but I hope to make another pass and bring the code-size down 

Anyway, thanks for the feedback again! 
    
</details>

Gives me some nice action points.

**Comment by Potherca** [comment]
On revisiting this one weekend later, I realized there are actually two consecutive use-cases

1. Displaying the menu on smaller screen width
2. Hiding the menu on smaller screen width and adding a mechanism to toggle the hidden menu

I think that use-case 1. should be resolved first, to give a uniform way the menu should look on smaller (mobile) screens without any hiding.

If/When that has been resolved, it would be trivial to create a toggle button. Whether that should then be part of core MVP.css is still up for debate. With styling for smaller screens, it might not even be needed...

The smallest CSS I could come up with, in order to display the menu on smaller screens, is:

```css
@media (max-width: 768px) {
  nav {
    flex-wrap: wrap; /* Allow the links to drop below the logo */
  }

  nav ul li {
    width: calc(100% - 1em); /* Make sure each link has enough room to have a separate line */
  }

  nav ul li ul {
    display: block; /* Make the sub-menus visible (as there is no "hover" on mobile) */
  }
}
```
The result (as can be seen on https://codepen.io/potherca/pen/abgRpGQ) is:

| Smaller screen | Even smaller screen |
| --- | --- |
| ![][1] | ![][2] |

[1]: https://github.com/user-attachments/assets/17dbb59b-1b91-48d3-b51c-deb6a30198ce
[2]: https://github.com/user-attachments/assets/2f907313-9b6f-4688-974b-1e006fe7c947

Various minor tweaks could be made, for instance:

- Remove the border on sub-menus: `nav ul li ul { border: none; box-shadow: none; }`
- Allow the sub-menus to have more width: `nav ul li ul { position: static; }`
- Make the link area clickable across the entire width: `nav ul li a { display: block; }`

I've added these tweaks commented out in the linked CodePen, so they can be played around with.

@ChristopherBilg Do you think I've missed anything?

**Comment by ChristopherBilg** [comment]
This is great. I agree that the first point is more important for MVP.css and that the second point, in my opinion, doesn't make sense to add unless it can be added in with the same level of seamlessness that you implemented the first point.

As far as this codepen goes, it looks great. I think for the minor tweaks, definitely the first for removing borders. I'm not in favor nor against the second minor tweaks, although as I play with the codepen, I'm wondering if we can make this functional for recursive depths of nested lists. I'm seeing distortion adding in another level.

![image](https://github.com/user-attachments/assets/04f679cd-debb-47b7-9383-f274e09de2a6)

**Comment by Potherca** [comment]
Yeah, I just did [a re-run with more (sub-)menu items][1] and I think the `nav ul li ul { position: static; }` will be a requirement in order to keep things working with larger menus. 

This will cause a large menu. The question then becomes whether that is okay or that a `max-height` and `overflow-y:auto;` will need to be added. Not sure yet 🤔 

Regarding shadows, without looks better IMHO.

| With shadow | Without shadow |
| --- | --- |
| ![][2] |![][3] |

Anyway, that would give us:

```css
@media (max-width: 768px) {
  nav {
    flex-wrap: wrap; /* Allow the links to drop below the logo */
  }

  nav ul li {
    width: calc(100% - 1em); /* Make sure each link has enough room to have a separate line */
  }

  nav ul li ul {
    border: none; box-shadow: none; /* Remove the shadow */
    display: block; /* Make the sub-menus visible (as there is no "hover" on mobile) */
    position: static; /* Make the menu-items stretch the whole width (excluding padding/margin */
  }
}
```
 
[1]: https://codepen.io/potherca/pen/mdZozpE
[2]: https://github.com/user-attachments/assets/670e0fea-4b0f-418d-8108-d3ea69e84c91
[3]: https://github.com/user-attachments/assets/35b9d5bc-cfcd-43d2-8743-7f2807ef5e8e
