### ISSUE TITLE
Responsive Menu for Mobile Screens

### ISSUE THREAD

**Issue by DennisSuitters** [andybrewer/mvp#21]
Hi Andy, I've come up with a way to produce a collapsible menu similar to how Bootstrap does `<nav/>` menus between large screen and smaller mobile device screens:
I was going to do a PR for this, but I figured you might want to modify it for your needs.
All good if you can't or don't want to use it, I just remember someone asking about responsiveness, and I just built this for my own needs to incorporate mvp.css as a complete theme for my CMS, and having to add some features which I'm trying to do along the mvp style with very, very minimum classes.
````html
<nav role="mobile-menu">
  <input type="checkbox" id="mobile-menu">
  <label for="mobile-menu" onclick>Menu</label>
  <ul>
    <li>Menu Item</li>
  </ul>
</nav>
````

````css
/* Mobile Responsive Menu */
nav[role="mobile-menu"] {
  display: flex;
}

nav[role="mobile-menu"] input[type=checkbox] {
  display: none;
}

nav[role="mobile-menu"] label {
  display: none;
  cursor: pointer;
  user-select: none;
}

nav[role="mobile-menu"] {
  position: relative;
  width: 100%;
}

nav[role="mobile-menu"] ul {
  padding: 0;
  margin: 0 auto;
  list-style: none;
}

@media screen and (max-width: 44em) {
  nav[role="mobile-menu"] {
    display: block;
    align-items: flex-start;
  }

  nav[role="mobile-menu"] ul {
    display: none;
  }

  nav[role="mobile-menu"] label {
    position: relative;
    display: block;
    width: 100%;
    border-radius: var(--border-radius);
    display: inline-block;
    font-size: medium;
    font-weight: 700;
    line-height: var(--line-height);
    margin: .75rem 0 .25rem 0;
    padding: .5rem 1rem;
    font-family: var(--font);
    background-color: var(--color);
    border: 2px solid var(--color);
    color: var(--color-bg);
  }

  nav[role="mobile-menu"] label:hover {
    cursor: pointer;
    filter: brightness(var(--hover-brightness));
  }

  nav[role="mobile-menu"] input[type=checkbox]:checked ~ ul {
    display: block;
    // styles to make an animated drop can be added here.
  }

  nav[role="mobile-menu"] input[type=checkbox]:checked ~ ul li {
    width: 100%;
  }
}
````

![screencapture-localhost-AuroraCMS-2020-04-06-00_17_37](https://user-images.githubusercontent.com/32765473/78501053-6669c500-779d-11ea-97db-575a5595ff3d.png)

![Peek 2020-04-06 00-25](https://user-images.githubusercontent.com/32765473/78501063-6ff32d00-779d-11ea-80cd-9c513a6d4f4b.gif)
