### ISSUE TITLE
Styling links as buttons using role="button"

### ISSUE THREAD

**Issue by DennisSuitters** [andybrewer/mvp#26]
Hi Andy, while I was working on building a theme around mvp, I realised that styling links as buttons changes their role, I assume your aware that when elements are used in a manner not original to their specs that we can use the `role=""` attribute to indicate to screen readers, and validators what the presentation is intended for that element. So, I had a look at styling anchor's used as buttons using the `role="button"` attribute rather than the current styling using `a b` or `a strong` (and seeing as the buttons are already having their font-weight set to bold), they look exactly the same, also, using the role attribute helps indicate in the html markup exactly what that element is doing or being used for.

````css
a[role="button"],
button {
    border-radius: var(--border-radius);
    display: inline-block;
    font-size: medium;
    font-weight: bold;
    line-height: var(--line-height);
    margin: 1.5rem 0 0.5rem 0;
    padding: 1rem 2rem;
}
````

````html
<a href="#" role="button"><i>Italic Link Button</i></a>
<a href="#" role="button">Bold Link Button &rarr;</a>
````
As you can see, we can do away with the extra classes, but still use them if we wish to change the text, and using the role attributes makes sure our markup is valid and represented correctly.

Anyway, some food for thought.

I also had an idea for my own purposes and needing things like for e.g. a jumbotron (ala Bootstrap), we can use the role attribute on a section element, with it's siblings being styled accordingly without the need to add classes, plus that would also indicate what that block of code does within the markup.
