### ISSUE TITLE
Why is the dark mode commented-out?

### ISSUE THREAD

**Issue by cizordj** [andybrewer/mvp#70]
I have noticed that in your last release, the code responsible for the dark theme is commented-out.

```css
/*
@media (prefers-color-scheme: dark) {
    :root {
        --color: #0097fc;
        --color-accent: #0097fc4f;
        --color-bg: #333;
        --color-bg-secondary: #555;
        --color-secondary: #e20de9;
        --color-secondary-accent: #e20de94f;
        --color-shadow: #bbbbbb20;
        --color-text: #f7f7f7;
        --color-text-secondary: #aaa;
    }
}
*/
```
and your [commit](https://github.com/andybrewer/mvp/commit/a19b86a73a565090e010cdaf537daa9fd977da06) regarding this change does not explain why it was commented.

I started to use this CSS library and I had modify it in order to enable the dark theme, I was just wondering why it was not enabled by default.

Thanks.
